name: Build Base Images

on:
  push:
    branches: [main]
    paths:
      - 'docker/**'
      - '.github/workflows/build-base-images.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  GHCR_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: ubuntu
            version: 22.04
            arch: amd64

          - distro: ubuntu
            version: 22.04
            arch: arm64

          - distro: debian
            version: 12
            arch: amd64

          - distro: debian
            version: 12
            arch: arm64

          - distro: fedora
            version: 39
            arch: amd64

          - distro: fedora
            version: 39
            arch: arm64

          - distro: rocky
            version: 9
            arch: amd64

          - distro: rocky
            version: 9
            arch: arm64

          - distro: alpine
            version: 3.18
            arch: amd64

          - distro: alpine
            version: 3.18
            arch: arm64

          - distro: raspbian
            version: 2024
            arch: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image ${{ matrix.distro }}:${{ matrix.version }}-${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ matrix.distro }}
          file: ./docker/${{ matrix.distro }}/Dockerfile.${{ matrix.distro }}-base
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/sysadmin-sim-${{ matrix.distro }}-base:${{ matrix.distro }}-${{ matrix.version }}-${{ matrix.arch }}
            ${{ env.GHCR_REGISTRY }}/sysadmin-sim-${{ matrix.distro }}-base:latest-${{ matrix.arch }}
